worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  text/html;

    access_log /dev/stdout;
    error_log  /dev/stderr notice;

    server {
        listen 80;
        server_name lab-web-tls secure.lab.local;

        add_header X-WWCA-Lab "http-cleartext" always;

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
    }

    server {
        listen 443 ssl;
        server_name secure.lab.local;

        ssl_certificate     /etc/nginx/certs/secure.lab.local.crt;
        ssl_certificate_key /etc/nginx/certs/secure.lab.local.key;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers off;

        add_header X-WWCA-Lab "https-tls" always;

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
    }
}
